def get_expenses():

    expenses = []

    while True:

        expense_type = input("Enter expense type (or 'done' to finish): ")

        if expense_type.lower() == 'done':

            break

        amount = float(input("Enter amount: $"))

        expenses.append((expense_type, amount))

    return expenses

def calculate_total(expenses):

    amounts = [expense[1] for expense in expenses]

    return reduce(lambda x, y: x + y, amounts, 0)
...
... def highest_expense(expenses):
...
...     return max(expenses, key=lambda x: x[1])
...
... def lowest_expense(expenses):
...
...     return min(expenses, key=lambda x: x[1])
...
... def display_results(expenses):
...
...     total = calculate_total(expenses)
...
...     highest = highest_expense(expenses)
...
...     lowest = lowest_expense(expenses)
...
...     print("\nMonthly Expense Summary")
...
...     print("-" * 30)
...
...     print(f"Total Expenses: ${total:.2f}")
...
...     print(f"Highest Expense: {highest[0]} - ${highest[1]:.2f}")
...
...     print(f"Lowest Expense: {lowest[0]} - ${lowest[1]:.2f}")
...
... def main():
...
...     expenses = get_expenses()
...
...     if len(expenses) == 0:
...
...         print("No expenses entered.")
...
...     else:
...
...         display_results(expenses)